from . import society
from . import block
from . import plot   
from . import nominee    
from . import transfer 
from . import ledger
from . import installment
from . import housing_file
from . import member
from . import refund_wizard
from . import plot_allotment
from . import account_move
from . import settings
from . import res_config_settings